os: linux
language: cpp
compiler: g++

jobs:
  include:
    - os: linux
      dist: focal

notifications:
  email:
    recipients:
      - andreapatrizi1b6e6@gmail.com
    on_success: never
    on_failure: always

before_script:
- rm -rf /opt/pyenv  # damn pyenv

# apt update and core packages installation
- sudo apt-get update
- sudo apt-get install git libgtest-dev cmake libeigen3-dev pybind11-dev lsb-release

script: 
- set +e
- mkdir build
- cd build
- UBUNTU_MAJOR_FULL=$(lsb_release -rs)
- WITH_TESTS=ON
- if echo "$UBUNTU_MAJOR_FULL" | grep -q "18"; then WITH_PYTHON='OFF'; else WITH_PYTHON='ON'; fi
- cmake ../SharsorIPCpp/ -DWITH_TESTS=$WITH_TESTS -DWITH_PYTHON=$WITH_PYTHON ..
- make
- ctest --output-on-failure
